use medical;
ALTER TABLE `table` 
CHANGE `subcounty` 
`subcounty` ENUM('CHANGAMWE','JOMVU 
','KISAUNI 
','LIKONI 
','MVITA (MOMBASA) 
','NYALI 
','KINANGO 
','KWALE 
','LUNGA LUNGA 
','MSAMBWENI 
','BAHARI (KILIFI) 
','GANZE 
','KALOLENI 
','KILIFI SOUTH 
','MAGARINI 
','MALINDI 
','RABAI 
','BURA (TANA NORTH) 
','TANA DELTA 
','TANA RIVER 
','LAMU EAST 
','LAMU WEST 
','MWATATE 
','TAVETA 
','VOI 
','WUNDANYI (TAITA) 
','BALAMBALA 
','DADAAB 
','FAFI 
','GARISSA 
','HULUGHO 
','IJARA 
','LAGDERA 
','BUNA 
','ELDAS 
','HABASWEIN 
','TARBAJ 
','WAJIR EAST 
','WAJIR NORTH 
','WAJIR SOUTH 
','WAJIR WEST 
','BANISA 
','LAFEY 
','MANDERA CENTRAL 
','MANDERA EAST 
','MANDERA NORTH 
','MANDERA WEST 
','CHALBI 
','HORR NORTH 
','LOIYANGALANI 
','MARSABIT 
','MARSABIT SOUTH (LAISAMIS) 
','MOYALE 
','SOLOLO 
','GARBATULA 
','ISIOLO 
','MERTI 
','BUURI 
','IGEMBE CENTRAL 
','IGEMBE NORTH 
','IGEMBE SOUTH 
','IMENTI NORTH 
','IMENTI SOUTH 
','MERU CENTRAL 
','TIGANIA CENTRAL 
','TIGANIA EAST 
','TIGANIA WEST 
','MAARA 
','MERU SOUTH 
','THARAKA NORTH 
','THARAKA SOUTH 
','EMBU EAST 
','EMBU NORTH 
','EMBU WEST 
','MBEERE NORTH 
','MBEERE SOUTH 
','IKUTHA 
','KATULANI 
','KISASI 
','KITUI CENTRAL 
','KITUI WEST 
','KYUSO 
','LOWER YATTA 
','MATINYANI 
','MUMONI 
','MUTITO 
','MUTOMO 
','MWINGI CENTRAL 
','MWINGI EAST 
','MWINGI WEST /MIGWANI 
','NZAMBANI 
','TSEIKURU 
','ATHI RIVER 
','KANGUNDO 
','KATHIANI 
','MACHAKOS 
','MASINGA 
','MATUNGULU 
','MWALA 
','YATTA 
','KATHONZWENI 
','KIBWEZI 
','KILUNGU 
','MAKINDU 
','MAKUENI 
','MBOONI EAST 
','MBOONI WEST 
','MUKAA 
','NZAUI 
','KINANGOP 
','KIPIPIRI 
','MIRANGINE 
','NYANDARUA CENTRAL 
','NYANDARUA NORTH 
','NYANDARUA SOUTH 
','NYANDARUA WEST 
','KIENI EAST 
','KIENI WEST 
','MATHIRA EAST 
','MATHIRA WEST 
','MUKURWE-INI 
','NYERI CENTRAL 
','NYERI SOUTH 
','TETU 
','KIRINYAGA CENTRAL 
','KIRINYAGA EAST 
','KIRINYAGA WEST 
','MWEA EAST 
','MWEA WEST 
','GATANGA 
','KAHURO 
','KANDARA 
','KANGEMA 
','KIGUMO 
','MATHIOYA 
','MURANG\'A EAST 
','MURANG\'A SOUTH 
','GATUNDU NORTH 
','GATUNDU SOUTH 
','GITHUNGURI 
','JUJA 
','KABETE 
','KIAMBAA 
','KIAMBU 
','KIKUYU 
','LARI 
','LIMURU 
','RUIRU 
','THIKA EAST 
','THIKA WEST 
','KIBISH 
','LOIMA 
','TURKANA CENTRAL 
','TURKANA EAST 
','TURKANA NORTH 
','TURKANA SOUTH 
','TURKANA WEST 
','KIPKOMO 
','POKOT CENTRAL 
','POKOT NORTH 
','POKOT SOUTH 
','WEST POKOT 
','SAMBURU CENTRAL 
','SAMBURU EAST 
','SAMBURU NORTH 
','ENDEBES 
','KIMININI 
','KWANZA 
','TRANS NZOIA EAST 
','TRANS NZOIA WEST 
','ELDORET EAST 
','ELDORET WEST 
','KESSES 
','MOIBEN 
','SOY 
','WARENG 
','KEIYO 
','KEIYO SOUTH 
','MARAKWET EAST 
','MARAKWET WEST 
','CHESUMEI 
','NANDI CENTRAL 
','NANDI EAST 
','NANDI NORTH 
','NANDI SOUTH 
','TINDERET 
','BARINGO CENTRAL 
','BARINGO NORTH 
','EAST POKOT 
','KOIBATEK 
','MARIGAT 
','MOGOTIO 
','LAIKIPIA CENTRAL 
','LAIKIPIA EAST 
','LAIKIPIA NORTH 
','LAIKIPIA WEST 
','NYAHURURU 
','GILGIL 
','KURESOI 
','KURESOI NORTH 
','MOLO 
','NAIVASHA 
','NAKURU EAST 
','NAKURU NORTH 
','NAKURU WEST 
','NJORO 
','RONGAI 
','SUBUKIA 
','NAROK EAST 
','NAROK NORTH 
','NAROK SOUTH 
','NAROK WEST 
','TRANS MARA EAST 
','TRANS MARA WEST 
','ISINYA 
','KAJIADO CENTRAL 
','KAJIADO NORTH 
','KAJIADO WEST 
','LOITOKITOK 
','MASHUURU 
','BELGUT 
','BURETI 
','KERICHO 
','KIPKELION 
','LONDIANI 
','SIGOWEI / SOIN 
','BOMET 
','BOMET EAST 
','CHEPALUNGU 
','KONOIN 
','SOTIK 
','BUTERE 
','KAKAMEGA CENTRAL 
','KAKAMEGA EAST 
','KAKAMEGA NORTH 
','KAKAMEGA SOUTH 
','KHWISERO 
','LIKUYANI 
','LUGARI 
','MATETE 
','MATUNGU 
','MUMIAS 
','MUMIAS EAST 
','NAVAKHOLO 
','EMUHAYA 
','HAMISI 
','LUANDA 
','SABATIA 
','VIHIGA 
','BUMULA 
','BUNGOMA CENTRAL 
','BUNGOMA EAST 
','BUNGOMA NORTH 
','BUNGOMA SOUTH 
','BUNGOMA WEST 
','CHEPTAIS 
','KIMILILI 
','MT ELGON 
','WEBUYE WEST 
','BUNYALA 
','BUSIA 
','BUTULA 
','NAMBALE 
','SAMIA 
','TESO NORTH 
','TESO SOUTH 
','BONDO 
','GEM 
','RARIEDA 
','SIAYA 
','UGENYA 
','UGUNJA 
','KISUMU CENTRAL 
','KISUMU EAST 
','KISUMU WEST 
','MUHORONI 
','NYAKACH 
','NYANDO 
','SEME 
','HOMA BAY 
','MBITA 
','NDHIWA 
','RACHUONYO EAST 
','RACHUONYO NORTH 
','RACHUONYO SOUTH 
','RANGWE 
','SUBA 
','AWENDO 
','KURIA EAST 
','KURIA WEST 
','MIGORI 
','NYATIKE 
','RONGO 
','SUNA WEST 
','URIRI 
','GUCHA 
','GUCHA SOUTH 
','KENYENYA 
','KISII CENTRAL 
','KISII SOUTH 
','KITUTU CENTRAL 
','MARANI 
','MASABA SOUTH 
','NYAMACHE 
','SAMETA 
','BORABU 
','MANGA 
','MASABA NORTH 
','NYAMIRA NORTH 
','NYAMIRA SOUTH 
','DAGORETTI 
','EMBAKASI 
','KAMUKUNJI 
','KASARANI 
','KIBRA 
','LANGATA 
','MAKADARA 
','MATHARE 
','NJIRU 
','STAREHE 
','WESTLANDS','' 
) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL;